### ISSUE TITLE
Can i like a tweet from this package ?

### ISSUE THREAD

**Issue by MatheeshaMe** [Rishikant181/Rettiwt-Core#155]
I am curious i can like a tweet using this package and also looking for how to create a post with this package thanks

**Comment by Rishikant181** [comment]
Liking is currently in alpha and will soon be entering stable release. As for creating a post, check out [this example](https://rishikant181.github.io/Rettiwt-Core/#md:4-getting-the-request-to-create-a-simple-text-tweet).

However, you might wanna check out [Rettiwt-API](https://github.com/Rishikant181/Rettiwt-API), which is basically a wrapper over this library. This library just generates axios request configs. In order to make a request, you need to authenticate too. Rettiwt-API handles all the shenanigans of making HTTP requests as well as authenticating, while providing simple functions to accomplish data fetching and posting tasks.
